### ISSUE TITLE
release new version with check-varnish included

### ISSUE THREAD

**Issue by warmfusion** [sensu-plugins/sensu-plugins-varnish#9]
I'm using tags to package gems into consistent deployments across out environment, but 0.0.5 doesn't include the check-varnish script.

Can you tag or release the latest version of this project for consistency?

**Comment by majormoses** [comment]
@warmfusion I encourage people to lock their versions of gems either via git or rubygem native methods as you are doing.

I am in the process of formally outlining when we should be releasing functional changes (does not include documentation, travis testing, rake tasks, etc).

IMHO I believe that there is no good reason that functional changes should ever take more than 24 hours to release after acceptance. Assuming the changelog is properly groomed it takes less than 15 minutes to cut a release (much of it waiting on CI) if you are familiar with the process. Currently most of the active maintainers on plugins do not work for sensu and have full time jobs elsewhere otherwise I would push for always immediate releases. In most cases I try to run releases immediately after accepting changes if not I will usually do it that evening after work. Until this get's formalized if someone else has merged and not released within 24 hours please ping me and the maintainer that merged it so I can release and bring this up.

@mbbroberg yet another case of why this needs to be formalized.

**Comment by majormoses** [comment]
@warmfusion taking a look at master and will update when I have a release cut.

**Comment by majormoses** [comment]
@warmfusion looks like tests are failing on ruby 1.9 so I cant really make a release to rubygems. I will create a git tag and will bump to a 1.x version with ruby 2.x support which will include the changes.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-varnish/versions/1.0.0

**Comment by majormoses** [comment]
@warmfusion I would like to apologize again for this, I hacked together the release to unblock you and if you are ever seeing this happen again please ping both the maintainer who merged the request and myself so I can address this.

**Comment by warmfusion** [comment]
@majormoses  - Thanks for this; No need to appologise i'm in a similar position with a plugin i contribute to for FluentD.
